In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [16]:
# Create the sequence of odd numbers
sequence = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61]

In [17]:
# Prepare the input and output data
X = np.array(sequence[:-1])  # Input sequence (excluding the last number)
y = np.array(sequence[1:])  # Output sequence (next number in the sequence)


In [18]:
y

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61])

In [19]:
# Define the model
model = Sequential()
model.add(Dense(10, input_dim=1, activation='relu'))
model.add(Dense(1, activation='linear'))

In [20]:
# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

In [21]:
# Train the model
model.fit(X, y, epochs=100, batch_size=1)

Epoch 1/100
30/30 [==============================] - 1s 2ms/step - loss: 1020.6758
Epoch 2/100
30/30 [==============================] - 0s 1ms/step - loss: 836.8094
Epoch 3/100
30/30 [==============================] - 0s 1ms/step - loss: 673.7444
Epoch 4/100
30/30 [==============================] - 0s 2ms/step - loss: 536.7481
Epoch 5/100
30/30 [==============================] - 0s 1ms/step - loss: 422.5301
Epoch 6/100
30/30 [==============================] - 0s 2ms/step - loss: 327.5437
Epoch 7/100
30/30 [==============================] - 0s 2ms/step - loss: 249.4334
Epoch 8/100
30/30 [==============================] - 0s 2ms/step - loss: 183.6662
Epoch 9/100
30/30 [==============================] - 0s 1ms/step - loss: 133.9710
Epoch 10/100
30/30 [==============================] - 0s 2ms/step - loss: 93.7584
Epoch 11/100
30/30 [==============================] - 0s 2ms/step - loss: 63.9267
Epoch 12/100
30/30 [==============================] - 0s 1ms/step - loss: 42.2024
Epoch 13/100
30

In [22]:
np.array([sequence[-2]])

array([59])

In [13]:
np.array([14])

array([14])

In [23]:
# Generate the prediction
next_number = model.predict(np.array([sequence[-2]]))
print("Predicted next number:", next_number)

1/1 [==============================] - 0s 63ms/step
Predicted next number: [[61.357357]]
